#!/usr/bin/env bash
# configures an Nginx server to listen on port 80.

# create a symbolic link (-s option) between the Nginx configuration file
# and then enabled sites directoy
ln -sf /ect/nginx/sites-available/default /ect/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | heaad -1)"
