#!/usr/bin/env bash
# This script fixes Nginx to listen on port 80 in a short and sweet way

# Update Nginx configuration to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
