#!/usr/bin/env bash
#SSH client configuration

Host *
    IdentityFile ~/.ssh/id_rsa
    PasswordAuthentication no
    SendEnv LANG LC_*
    HashKnownHosts yes 
    GSSAPIAuthentication yes  
    GSSAPIDelegateCredentials no
